export default {
  Black: 'Mulish-Black',
  BlackItalic: 'Mulish-BlackItalic',
  Bold: 'Mulish-Bold',
  BoldItalic: 'Mulish-BlackItalic',
  Italic: 'Mulish-Italic',
  Light: 'Mulish-Light',
  Medium: 'Mulish-Medium',
  MediumItalic: 'Mulish-MediumItalic',
  Regular: 'Mulish-Regular',
  SemiBold: 'Mulish-SemiBold',
  SemiBoldItalic: 'Mulish-SemiBoldItalic',
  Thin: 'Mulish-Light',
  ThinItalic: 'Mulish-LightItalic',
};
